name: Testing and linting Web Server

on:
#  pull_request:
#    branches:
#      - main
  workflow_dispatch:

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-compose.ci.yml
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build docker images
      run: docker-compose build

    - name: Run linters and tests
      run: docker-compose run service_lint_test